[tool.poetry]
name = "generate-embedding"
version = "0.1.0"
description = ""
authors = ["Lucian Hymer <github@lucianhymer.com>"]
readme = "README.md"
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.12"
sentence-transformers = "^3.2.1"
click = "^8.1.7"
xformers = "^0.0.28.post3"

[tool.poetry.dev-dependencies]
black = "*"

[tool.poetry.scripts]
generate_embedding = "src.main:generate_embedding"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
