[tool.poetry]
name = "generate-embedding"
version = "0.1.0"
description = ""
authors = ["Lucian Hymer <github@lucianhymer.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
sentence-transformers = "^3.2.1"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
