[tool.poetry]
name = "generate-embedding"
version = "0.1.0"
description = ""
authors = ["Lucian Hymer <github@lucianhymer.com>"]
readme = "README.md"
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
sentence-transformers = "^3.2.1"
click = "^8.1.7"
torch = "^2.5.1"
wheel = "^0.45.0"
torchvision = "^0.20.1"
redis = "^5.2.0"

[tool.poetry.dev-dependencies]
black = "*"

[tool.poetry.scripts]
generate_embedding = "src.main:generate_embedding"

[tool.poetry.group.dev.dependencies]
types-redis = "^4.6.0.20241004"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
